Namma_bazaar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),    
    path('securelogin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('order/', include('orders.urls')),
    
]+static (settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path,include
from carts import views

urlpatterns = [
    path('', views.cart_page, name='cart_page'),
    path('add-cart/<int:product_id>/', views.add_cart, name='add-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove-cart'),
    path('remove-cart-item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove-cart-item'),
    path('checkout/', views.checkout, name='checkout'),

    ]

store/urls.py
from django.urls import path
from store import views

urlpatterns = [
    
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name= 'products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name= 'product_detail'),
    path('search/',views.search, name='search'),
    path('submit_review/<int:product_id>',views.submit_review, name='submit_review'),

               
               
               
               ]

carts/models.py
from django.db import models
from store.models import product,product_variation
from accounts.models import Accounts


# Create your models here.

class cart( models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    added_date=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id
    
class cartItem(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    user=models.ForeignKey(Accounts, on_delete=models.CASCADE, null=True)
    variation=models.ManyToManyField(product_variation,blank=True)
    cart=models.ForeignKey(cart,on_delete=models.CASCADE, null=True)
    quantity=models.IntegerField()
    is_active=models.BooleanField(default=True)

    def __unicode__(self):
        return self.product
    
    def sub_total(self):
        return self.product.price * self.quantity
    

store/models.py
from django.db import models
from category.models import Category
from accounts.models import Accounts
from django.urls import reverse
from django.db.models import Avg,Count

# Create your models here.

class product (models.Model):
    product_name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=200,unique=True)
    description=models.TextField(max_length=500,blank=True)
    price=models.IntegerField()
    images=models.ImageField(upload_to='photos/products')
    stocks=models.IntegerField()
    is_available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    modified_date=models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.product_name
    
    def get_url (self):
        return reverse ('product_detail', args=[self.category.slug,self.slug])
    
    def average_rating(self):
        reviews=ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg=0
        if reviews['average'] is not None:
            avg=float(reviews['average'])
        return avg

    def review_count (self):
        review_count=ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count=0
        if review_count['count'] is not None:
            count=int(review_count['count'])
        return count

    
class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color', is_active=  True)
    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size', is_active=True)


variation_choices=(('color','color'),('size','size'))
class product_variation(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    variation_category=models.CharField( max_length=50,choices=variation_choices)
    variation_name=models.CharField(max_length=50)
    is_active=models.BooleanField(default=True)

    def __str__(self): 
        return self.variation_name
    
    objects=VariationManager()

class ReviewRating (models.Model):
    product=models.ForeignKey(product, on_delete=models.CASCADE)
    user=models.ForeignKey(Accounts, on_delete=models.CASCADE)
    subject=models.CharField(max_length=50, blank=True)
    review=models.TextField(max_length=500, blank=True)
    rating=models.FloatField()
    IP= models.CharField(max_length=40, blank=True)
    status=models.BooleanField(default=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    


class ProductGallery (models.Model):
    product=models.ForeignKey(product, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='store/products',max_length=30)

    def __str__(self):
        return self.product.product_name

    

store/forms.py
from django import forms
from store.models import ReviewRating

class ReviewRatingForm (forms.ModelForm):
    class Meta:
        model=ReviewRating
        fields= ['subject','review','rating']
        

carts/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from django.contrib.auth.decorators import login_required
from store.models import product,product_variation
from carts.models import cart,cartItem
# Create your views here.


def _cart_id(request):
    session_id = request.session.session_key
    if not session_id:
        session_id = request.session.create()
      # Assign the newly created session key
    return session_id



def add_cart (request,product_id):
    products=product.objects.get(id=product_id)
    current_user=request.user
    #if the user is authenticated
    if current_user.is_authenticated:
            product_variations=[]
            if request.method=='POST':
                for items in request.POST:
                    key=items
                    value=request.POST[key]
                    try:
                        variation_list=product_variation.objects.get(product=products, variation_category__iexact=key, variation_name__iexact=value)
                        product_variations.append(variation_list)
                    except:
                        pass


            is_cart_item_exists= cartItem.objects.filter(product=products,user=current_user).exists()
            if is_cart_item_exists:
                cart_item=cartItem.objects.filter(product=products, user=current_user)
                #need 1. existing variations 2. product variation(want to add) 3.item_id
                ex_var_list=[]
                id=[]
                for item in cart_item:
                    existing_variation=item.variation.all()
                    ex_var_list.append(list(existing_variation))
                    id.append(item.id)

                if product_variations in ex_var_list:
                    index=ex_var_list.index(product_variations)
                    item_id=id[index]
                    item=cartItem.objects.get(product=products, id=item_id)
                    item.quantity = item.quantity + 1 
                    item.save()
                        # increase quantity
                else:
                    item=cartItem.objects.create(product=products, user=current_user, quantity=1)
                    if len(product_variations) > 0 :
                        item.variation.clear()
                        item.variation.add(*product_variations)
                    item.save()

            else :
                cart_item=cartItem.objects.create(
                    product=products,
                    user=current_user,
                    quantity=1,
                )
                if len(product_variations) > 0 :
                    cart_item.variation.clear()
                    cart_item.variation.add(*product_variations)
                cart_item.save()
            return redirect ('cart_page')
    
    #  If the user is not authenticated   
    else:
        product_variations=[]
        if request.method=='POST':
            for items in request.POST:
                key=items
                value=request.POST[key]
                try:
                    variation_list=product_variation.objects.get(product=products, variation_category__iexact=key, variation_name__iexact=value)
                    product_variations.append(variation_list)
                except:
                    pass

        try:
            Cart=cart.objects.get(cart_id=_cart_id(request))
        except cart.DoesNotExist:
            Cart=cart.objects.create(
                cart_id=_cart_id(request)
            )
            Cart.save()



        is_cart_item_exists= cartItem.objects.filter(product=products,cart=Cart).exists()
        if is_cart_item_exists:
            cart_item=cartItem.objects.filter(product=products, cart=Cart)
            #need 1. existing variations 2. product variation(want to add) 3.item_id
            ex_var_list=[]
            id=[]
            for item in cart_item:
                existing_variation=item.variation.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variations in ex_var_list:
                index=ex_var_list.index(product_variations)
                item_id=id[index]
                item=cartItem.objects.get(product=products, id=item_id)
                item.quantity = item.quantity + 1 
                item.save()
                    # increase quantity
            else:
                item=cartItem.objects.create(product=products, cart=Cart, quantity=1)
                if len(product_variations) > 0 :
                    item.variation.clear()
                    item.variation.add(*product_variations)
                item.save()

        else :
            cart_item=cartItem.objects.create(
                product=products,
                cart=Cart,
                quantity=1,
            )
            if len(product_variations) > 0 :
                cart_item.variation.clear()
                cart_item.variation.add(*product_variations)
            cart_item.save()
        return redirect ('cart_page')

def remove_cart(request,product_id,cart_item_id ):
    products=get_object_or_404(product,id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item=cartItem.objects.get(user=request.user,product=products, id=cart_item_id)
        else:
            Cart=cart.objects.get(cart_id=_cart_id(request))
            cart_item=cartItem.objects.get(cart=Cart,product=products, id=cart_item_id)
        if cart_item.quantity > 1 :
            cart_item.quantity -=1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect ('cart_page')


def remove_cart_item (request,product_id,cart_item_id):
    products=get_object_or_404(product,id=product_id)
    if request.user.is_authenticated:
        cart_item=cartItem.objects.get(user=request.user,product=products,id=cart_item_id)
    else:
        Cart=cart.objects.get(cart_id=_cart_id(request))
        cart_item=cartItem.objects.get(cart=Cart,product=products,id=cart_item_id)
    cart_item.delete()
    return redirect('cart_page')

    

def cart_page (request,total=0,quantity=0,cart_item=None):
    try:
        tax=0
        grand_total=0
        if request.user.is_authenticated:
            cart_item=cartItem.objects.filter(user=request.user, is_active=True)
        else:
            Cart=cart.objects.get(cart_id=_cart_id(request))
            cart_item=cartItem.objects.filter(cart=Cart,is_active=True)
        for cart_items in cart_item:
            total=total + (cart_items.product.price * cart_items.quantity)
            quantity= quantity + cart_items.quantity
        tax= (3*total/100)
        grand_total=total+tax
        
    except :
        pass

    context={
        'cart_items':cart_item,
        'quantity':quantity,
        'total':total,
        'tax':tax,
        'grand_total':grand_total,
    }
    return render (request,'store/cart.html',context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_item=None):
    try:
        tax=0
        grand_total=0
        if request.user.is_authenticated:
            cart_item=cartItem.objects.filter(user=request.user, is_active=True)
        else:
            Cart=cart.objects.get(cart_id=_cart_id(request))
            cart_item=cartItem.objects.filter(cart=Cart,is_active=True)
        for cart_items in cart_item:
            total=total + (cart_items.product.price * cart_items.quantity)
            quantity= quantity + cart_items.quantity
        tax= (3*total/100)
        grand_total=total+tax
        
    except :
        pass

    context={
        'cart_items':cart_item,
        'quantity':quantity,
        'total':total,
        'tax':tax,
        'grand_total':grand_total,
    }
    return render (request,'store/checkout.html',context)

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from store.models import product, ReviewRating,ProductGallery
from category.models import Category
from carts.models import cartItem
from carts.views import _cart_id
from django.contrib import messages
from store.forms import ReviewRatingForm
from orders.models import OrderProduct

def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug is not None:
        categories = get_object_or_404(Category,slug=category_slug) #It will bring requested category
        products = product.objects.filter(category=categories, is_available=True)
         #It'll filter the products from above selected category
        paginators=Paginator(products,1)
        page=request.GET.get('page')
        page_product=paginators.get_page(page)
        product_count = products.count()
    else:
        products = product.objects.filter(is_available=True)
        product_count = products.count()
        paginators=Paginator(products,3)
        page=request.GET.get('page')
        page_product=paginators.get_page(page)

    context = {'products': page_product, 'product_count': product_count}

    return render(request, 'store/store.html', context)


def product_detail(request,category_slug,product_slug):
    try:
        single_product=product.objects.get(category__slug=category_slug, slug=product_slug)
        incart=cartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()


    except Exception as e :
        raise e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None
     
    #GETTING THE PRODUCT REVIEWS AND LIST ALL REVIEWS RELATED TO THAT PRODUCT
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    #GETTING THE PRODUCT GALLERY
    product_gallery= ProductGallery.objects.filter(product_id=single_product.id)


    context={'single_product':single_product, 'incart':incart, 'orderproduct':orderproduct, 'reviews':reviews, 'product_gallery':product_gallery }

    return render(request,'store/product_detail.html',context)

def search(request):
    if 'keyword' in request.GET:
        keyword=request.GET['keyword']
        if keyword:
            products=product.objects.order_by('-created_date').filter(Q(description__icontains=keyword)| Q (product_name__icontains=keyword))
    product_count = products.count()

                                                                
    context={'products':products,'product_count': product_count}

    return render (request,'store/store.html', context)

def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewRatingForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewRatingForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)

templates/store/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
<h2 class="text-center text-primary-light"> Please add something to your cart </h2>


{% else  %}
  
  
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for cart_item in cart_items %}
  
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{cart_item.product.images.url}}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
				<p class="text-muted small"> 
					{% if cart_item.variation.all %}
						{% for i in cart_item.variation.all  %}
							{{i.variation_category}} : {{i.variation_name}}
							{% if not forloop.last %}, {% endif %} <!-- Add comma if not the last variation -->

						{% endfor %}
					  
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'remove-cart' cart_item.product.id cart_item.id  %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{cart_item.quantity}}">
							<div class="input-group-append">
								<form action="{% url 'add-cart' cart_item.product.id %}" method="POST">
									{% csrf_token %}
									{% for item in cart_item.variation.all %}
									<input type="hidden" name="{{item.variation_category | lower}}" value="{{item.variation_name | capfirst }}">
									  
									{% endfor %}
									<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>

								</form>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">$ {{cart_item.sub_total}}</var> 
			<small class="text-muted"> {{cart_item.product.price}} </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="{% url 'remove-cart-item' cart_item.product.id cart_item.id %}" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}

</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">$ {{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> $ {{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static 'images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
{% endif %}

{% endblock %}

templates/store/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap mainImage">
            <center> <img src={{single_product.images.url}}></center>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
    <ul class="thumb">
        <li>
            <a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}" alt="Product Image"></a>
            {% for i in product_gallery %}
            <a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Product Image"></a>
            {% endfor %}
        </li>
    </ul>
            </aside>
            <main class="col-md-6 border-left">

  <form action="{% url 'add-cart' single_product.id %}" method="POST">
    {% csrf_token %}

    <article class="content-body">
    
    <h2 class="title">{{single_product.product_name}}</h2>
    <div class="rating-star mb-2">
        <span>
            <i class="fa fa-star{% if single_product.average_rating < 0.5 %}-o{% elif single_product.average_rating >= 0.5 and single_product.average_rating < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.average_rating < 1.5 %}-o{% elif single_product.average_rating >= 1.5 and single_product.average_rating < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.average_rating < 2.5 %}-o{% elif single_product.average_rating >= 2.5 and single_product.average_rating < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.average_rating < 3.5 %}-o{% elif single_product.average_rating >= 3.5 and single_product.average_rating < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.average_rating < 4.5 %}-o{% elif single_product.average_rating >= 4.5 and single_product.average_rating < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
            <span class="m-2"> {{single_product.review_count}} reviews</span>
            
        </span>
    </div>
    
    <div class="mb-3"> 
        <var class="price h4">$ {{single_product.price}}</var> 
    </div> 
    
    <p>{{single_product.description}}</p>
    
    
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                <select name="color" class="form-control" required>
                  <option value="" disabled>select</option>

                  {% for i in single_product.product_variation_set.colors %}
                  <option value="{{i.variation_name | lower}}">{{i.variation_name|capfirst}}</option>
                  {% endfor %}
                 
                </select>
            </div>
        </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">

                <h6>Select Size</h6>
                <select name="size" class="form-control">
                  <option value="" disabled>select</option>

                  {% for i in single_product.product_variation_set.sizes %}
                  
                  <option value="{{i.variation_name | lower}}">{{i.variation_name|capfirst}}</option>
                    
                  {% endfor %}
                </select>
                
            </div>
        </div> <!-- row.// -->
        <hr>
        {% if single_product.stocks <= 0 %}
        <h5 class='text-danger'>*out of stock*</h5>
        {% else %}
          
        <button class="btn btn-primary" type="submit"> Add to cart</button>

        {% endif %}
    </article>
  </form>
   <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        
            
        </header>

        <form action="{% url 'submit_review' single_product.id %}" method="POST">
            {% csrf_token %}
            <h5>Write your reviews</h5>

            <div>
                <!-- star rating -->

                <label>How do you rate this product</label><br>
                <div class="rate">
                    <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
                    <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
                    <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
                    <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
                    <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
                    <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
                    <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
                    <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
                    <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
                    <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
                </div>
                <br>
                Review Title:
                <input type="text" name="subject" class="form-control" >
                Review:
                <textarea name="review" rows="8" class="form-control"></textarea>
                <br>

                {% if user.is_authenticated %}
                    {% if orderproduct %}
                            <input type="submit" value="Submit Review" class="btn btn-primary"><br>
                    {% else %}
                            <p><strong>***You must have purchased this product to post a review***</strong></p>
                    {% endif %} 
                {% else %}
                    <p><strong>***You should be logged in to post a review ***</strong> </p>
                {% endif %}
                        <br><br>

                {% include "includes/alert.html" %}

                


            </div>

        </form> <br>

        <header class="section-heading">
            <h3>Customer Reviews </h3>
            <div class="rating-star mb-3">
                <span>
                    <i class="fa fa-star{% if single_product.average_rating < 0.5 %}-o{% elif single_product.average_rating >= 0.5 and single_product.average_rating < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.average_rating < 1.5 %}-o{% elif single_product.average_rating >= 1.5 and single_product.average_rating < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.average_rating < 2.5 %}-o{% elif single_product.average_rating >= 2.5 and single_product.average_rating < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.average_rating < 3.5 %}-o{% elif single_product.average_rating >= 3.5 and single_product.average_rating < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.average_rating < 4.5 %}-o{% elif single_product.average_rating >= 4.5 and single_product.average_rating < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <span> {{single_product.review_count}} reviews</span>        
                </span>
            </div>
            
    {% for review in reviews  %}
      
        <article class="box mb-3">
            <div class="icontext w-100">
                <!-- <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle"> -->
                <div class="text">
                    <span class="date text-muted float-md-right">{{review.created_at}} </span>  
                    <h6 class="mb-1"> {{review.user.full_name}}</h6>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                        </span>
                    </div>
    
                </div>
            </div> <!-- icontext.// -->
            <h6 class="mt-3">{{review.subject}}</h6>
            <div class="mt-3">
                <p>
                    {{review.review}} 
                </p>	
            </div>
        </article>

    {% endfor %}

        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
{% endblock %}